name: corsten
favicon: null
layout_spectrum: 0.08383481344208121
typography_spectrum: 0.6314499147702008
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8719954511616379
  lightness: 0.22586542437784374
  saturation: 0.5064539783634245
  rhythmicContrast: 0.16107842605561018
purpose: []
